### ISSUE TITLE
NZXT Aer RBG and/or Hue+ support?

### ISSUE THREAD

**Issue by EliteL0jik** [CyanLabs/RGBSync#11]
I could guess that you probably get a number of people asking this question but are there any plans for adding support for NZXT items (case fans) at all?

If not, and you happen to know a way to connect NZXT to ASUS Aura, I would appreciate a nudge in the right direction.    ;)

Thanks-
L0jik

**Comment by Fma965** [comment]
Please contact https://github.com/DarthAffe/RGB.NET not RGBSync as we use RGB.net library.
