### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by khjdhghs** [CyanLabs/RGBSync#23]
Application crashes randomly under no load. It will be working fine until it crashes after 10 minutes- 1 hour. Not sure how to fix this issue but I don't think its my computer.

**Comment by khjdhghs** [comment]
I am using an asus z390-e mobo and cpu is 9600k. I am mainly trying to sync the mobos lights with corsairs. It works but not sure why it freezes/crashes.

**Comment by Fma965** [comment]
application is not supported please use rgbsyncplus as mentioned on the github readme.
