### ISSUE TITLE
Corsair K55 and Harpoon support

### ISSUE THREAD

**Issue by zstorm4** [CyanLabs/RGBSync#3]
Could support for these devices be added? And if there is support, it isn't working on a fresh windows install.

**Comment by Fma965** [comment]
any support requests should be directed to https://github.com/DarthAffe/RGB.NET/ as i use his library to provide support, i would assume k55 is already working though.

**Comment by mattmartinolc** [comment]
My K55 doesn't get controlled by the RGBsync program either.

**Comment by Fma965** [comment]
as per my previous comment any support requests should be directed to https://github.com/DarthAffe/RGB.NET/ as i use his library to provide support, i would assume k55 is already working though.
