### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by mattmartinolc** [CyanLabs/RGBSync#4]
Hi there. I love this program but am having issues. Had it working last night and my Strix motherboard, Strix 1080Ti, TridentZ RGB ram, Deep cool LED strips (aura) and my 6x HD120 corsair fans (hooked up to commander pro) were all synchronized and working from Asus Aura. The only thing that didn't seem to be synchronized was my Corsair K55 keyboard but that was a separate problem. 

Not sure what happened but now I cannot get RGBsync program to work. It looks to be running and shows up in the tray, but I cannot click it or bring up the settings and Corsair seems to be controlling. I uninstalled RGBsync, Aura, CUE, and Link and reinstalled everything but no luck. Am I supposed to have all the asus and corsair programs already running to run RGBsync or do I leave them closed?

**Comment by Fma965** [comment]
Link needs to be not running, Cue needs to be running with SDK enabled, Aura also needs to be running, you may try deleted the rgbsync folders from C:\Users\%username%\AppData\Local\Cyanlabs

**Comment by mattmartinolc** [comment]
It turned out it was a problem with the aura program not detecting the mobo. I toggled the RGB headers on/off in my bios and let it re-detect the hardware. Seems to work again. Now the only issue is it does not seem to be controlling the K55 keyboard, even though in CUE it tells me it is being controlled by the third party program.

**Comment by Fma965** [comment]
Aura does this sometimes, usually completely removing power frmo the pc fixes it, (removing psu cable / turning off psu)
