### ISSUE TITLE
error

### ISSUE THREAD

**Issue by billynano** [CyanLabs/RGBSync#6]
i cant see use aura devices in my RGBsync, can you send the link?

**Comment by Fma965** [comment]
thats not an error, it requires Aura so there is no option to disable Aura

**Comment by billynano** [comment]
i need to sync aura, my devices only sync corsair link and corsair cue.
aura isnt sync together

**Comment by Fma965** [comment]
Full system details required, motherboard, gpu, ram, link devices, cue devices etc etc

also please note as per the description on my website this only works if you have Asus Aura Motherboard

**Comment by billynano** [comment]
-spec
proc: amd ryzen 1800x
mobo: asus crosshair vi hero
gpu: asus rog strix 1080ti
ram: corsair vengeance 64gb
-cue devices:
keyboard; corsair k95 platinum
mouse: corsair scimitar pro
mousepad: mm800
headset: corsair void wireless special edition yellow jacket
-link devices:
controller : corsair commander pro
fans : corsair sp120rgb

absolutely have asus aura. but when RGBsync launched, only cue devices and
link devices that synced. motherboard and gpu doesnt sync.

**Comment by Fma965** [comment]
How many different LED zones do you have on your motherboard?

**Comment by billynano** [comment]
only two, maybe, here some picture

**Comment by Fma965** [comment]
no picture attached

**Comment by billynano** [comment]
two zone, 1 on backpanel, 1 on vrm heatsink beside pcie

**Comment by slickerxcuh** [comment]
Billy Try this

DELETE directory for RGBSync and do a fresh install but change the directory to for example RGBSync1 or RGBSync2 instead of the default, and when running Aura check to see if Mobo/DRAM is showing as well if not you may need to unplug power supply and do a power drain, to reset that.  I have Corsair CUE/Link synced up to Asus Aura and its beautiful.

**Comment by Fma965** [comment]
Whats the issue exactly? the colours not changing or changing to white or what?

**Comment by billynano** [comment]
slickerxcuh and Fma965

how to do that bro? when i launch rgbsync, my peripheral and corsair link devices are turn into white. and the motherboard and gpu still listening to music setting.

**Comment by Fma965** [comment]
Closed, can't fix - https://rog.asus.com/forum/showthread.php?97533-Calling-GetMBColor-returns-only-white

#7
