### ISSUE TITLE
RGBsync isn't working for me.

### ISSUE THREAD

**Issue by Kunai3X** [CyanLabs/RGBSync#7]
I boot it up, check my things (corsair link and logitech) and then click save settings, nothing, things just turn wait, except for my keyboard which just, stays purple, Help would be greatly appreciated. 

CPU: AMD Ryzen 7 1700. @ 3.75GHz. @ 1.30 Volts.
CPU Cooler: Deepcool Captain 240EX RGB.
Motherboard: ASUS Prime X370 Pro.
RAM: Crucial Ballistix Sport DRR4 16GB Red. @ 2400MHz.
GPU: ASUS GeForce GTX 1060 6GB DUAL OC. @ Stock.
Storage: 1TB Samsung 850 SSD, 240GB HYPERX Savage SSD.
PSU: EVGA 650GQ Semi-Modular 80+ PSU.
Case: Fractal Design Meshify C.
Accessories / Other 
Corsair LL120 3pack with Lightning Node Pro.
Corsair RGB LED Lighting Pro Expansion Kit.

**Comment by Fma965** [comment]
What effect do you have set in Aura

**Comment by Kunai3X** [comment]
Music: Normal

**Comment by Kunai3X** [comment]
I tried reinstalling and doing a complete power drain, and now RGBsync is giving me this lovely error

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.TimeoutException: Operation timed out.
   at RGBSync.Settings.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RGBSync
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGBSync.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2633.0 built by: NET471REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
RGB.NET.Core
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Core.DLL
----------------------------------------
RGB.NET.Devices.Asus
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Asus.DLL
----------------------------------------
RGB.NET.Groups
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Groups.DLL
----------------------------------------
RGB.NET.Devices.Razer
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Razer.DLL
----------------------------------------
RGB.NET.Devices.Msi
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Msi.DLL
----------------------------------------
RGB.NET.Devices.CorsairLink
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CorsairLink.DLL
----------------------------------------
RGB.NET.Devices.Novation
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Novation.DLL
----------------------------------------
RGB.NET.Devices.CoolerMaster
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.CoolerMaster.DLL
----------------------------------------
RGB.NET.Devices.Logitech
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Logitech.DLL
----------------------------------------
RGB.NET.Devices.Corsair
    Assembly Version: 0.0.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/RGB.NET.Devices.Corsair.DLL
----------------------------------------
System.ValueTuple
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
HidSharp
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/RGBSync/HidSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Kunai3X** [comment]
Okay so i'm not getting the unhandled exception anymore, and i'm back to everything being just white.

**Comment by zstorm4** [comment]
Isn't there a bug with ryzen motherboards and the reported colors or
something?

**Comment by Kunai3X** [comment]
if you mean with just the softwares themselves then no, corsair link and aura are working perfectly fine by themselves, if you're talking about RGBsync, i'd sure hope not.

**Comment by zstorm4** [comment]
No I mean like aura reports a separate device or something. I was trying to
sync a Corsair keyboard and mouse with a ryzen board and it wouldn't work
properly. That's the explanation given to me by darthaffes.

**Comment by Kunai3X** [comment]
I wouldn't know, i'm sorry.

**Comment by Fma965** [comment]
@Kunai3X @zstorm4 is right some boards report either black or white, join the discord and we can diagnose further https://discord.gg/5EcSpFP

**Comment by Fma965** [comment]
Closed, can't fix - https://rog.asus.com/forum/showthread.php?97533-Calling-GetMBColor-returns-only-white
